#
# ntu-sc2207
# Docker Compose
#

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU12-GDR1-ubuntu-20.04
    ports:
      - "1433:1433"
    volumes:
      - ./:/src
    environment:
      ACCEPT_EULA: Y
      # pass mssql password from env file
      MSSQL_SA_PASSWORD:
    network_mode: host
