-- PropertyOwner table
CREATE TABLE PROPERTYOWNER (
    NRIC VARCHAR(9) PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    CONTACTNUM VARCHAR(20) UNIQUE NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    AGE INT CHECK (AGE > 0)
);
