#
# CI Pipeline
#

name: CI Pipeline
on: push
jobs:
  lint:
    name: Lint SQL
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
          # cache pip dependencies
          cache: "pip"
      - name: Install pip dependencies
        run: pip install -r requirements.txt

  test:
    name: Test SQL on MS SQL Server DB
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Start DB container
        env:
          MSSQL_SA_PASSWORD: "${{ secrets.MSSQL_SA_PASSWORD }}"
        run: docker compose up -d
      - name: Wait for DB to be ready
        uses: iFaxity/wait-on-action@v1.2.1
        with:
          resource: tcp:localhost:1433
          interval: 5000 # pool every 5s
          timeout: 90000 # timeout in 90s
          verbose: true
      - name: Execute SQL DDL on DB
        run: sqlcmd -S "tcp:localhost,1433" -d mprops -U sa -P "${{ secrets.MSSQL_SA_PASSWORD }}" -i ddl.sql
      - name: Execute INSERTs on DB
        run: sqlcmd -S "tcp:localhost,1433" -d mprops -U sa -P "${{ secrets.MSSQL_SA_PASSWORD }}" -i data.sql
      - name: Execute Queries on DB
        run: sqlcmd -S "tcp:localhost,1433" -d mprops -U sa -P "${{ secrets.MSSQL_SA_PASSWORD }}" -i queries.sql
